AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
  DisplayCopNames: true
  TargetRailsVersion: 5.0

Rails:
  Enabled: true

Documentation:
  Enabled: false
