AllCops:
  Exclude:
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - bin/**/*
    - config/environments/*
  DisplayCopNames: true
  TargetRailsVersion: 5.0

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']

Metrics/MethodLength:
  Exclude:
    - 'app/graphql/fields/**/*'
